<#
.SYNOPSIS
  Compiles Silhouette's Papyrus scripts: the generated player picker (Player),
  the regeneration window (Adopter), and Phase 2's Plugin, Bridge and API.

.DESCRIPTION
  Compiles papyrus/ into build/papyrus/ against the reconstructed base sources and
  the import-only stubs in papyrus-stubs/ (LooksMenu's BodyGen, MCM). Adapted from
  fo4-chemistry/scripts/build-papyrus.ps1, which is known to work on this machine.

  papyrus/Silhouette/Player.psc is GENERATED by tools/silhouette_gen.py --write.
  Run that first.

  NEVER compile into Data/Scripts. That directory is Vortex-deployed.

  ASCII only. Windows PowerShell 5.1 reads a BOM-less UTF-8 script as ANSI, and one
  non-ASCII character in a string is enough to turn this into a parse error that
  still exits 0.
#>
[CmdletBinding()]
param(
    [string] $Base     = 'D:\F4CustomMods\PapyrusBase\Source\Base',
    [string] $Compiler = 'D:\GOGGames\Fallout 4 GOTY\Papyrus Compiler\PapyrusCompiler.exe'
)

$ErrorActionPreference = 'Stop'
$root    = Split-Path -Parent $PSScriptRoot
$sources = Join-Path $root 'papyrus'
$out     = Join-Path $root 'build\papyrus'
$stubs   = Join-Path $root 'papyrus-stubs'

if (-not (Test-Path $Compiler)) {
    throw "No Papyrus compiler at $Compiler."
}
if (-not (Test-Path (Join-Path $Base 'Institute_Papyrus_Flags.flg'))) {
    throw "No Institute_Papyrus_Flags.flg in $Base."
}
if (-not (Test-Path (Join-Path $sources 'Silhouette\Player.psc'))) {
    throw "No papyrus\Silhouette\Player.psc - run: python tools/silhouette_gen.py --write"
}

New-Item -ItemType Directory -Force -Path $out | Out-Null
$scripts = Get-ChildItem -Recurse -Filter *.psc $sources
Write-Host "Compiling $($scripts.Count) script(s) against $Base"

# Batch mode, not file by file: a namespaced script (Silhouette:Player) compiled by
# path fails with "filename does not match script name". The namespace has to come
# from the import paths, which -all does and a single file path cannot.
$output = & $Compiler $sources -all -f="Institute_Papyrus_Flags.flg" -i="$Base;$sources;$stubs" -o="$out" 2>&1

# Print everything the compiler said: a filtered view once hid the only line that
# explained a failure.
$output | ForEach-Object { Write-Host "  $_" }

$built = Get-ChildItem -Recurse -Filter *.pex $out -ErrorAction SilentlyContinue
Write-Host ""
Write-Host "$($built.Count) .pex in $out"
if ($output -match 'compilation failed' -or $output -match '0 succeeded') { exit 1 }
